# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://www.triadsmp.xyz"
baseurl: "/"
siteIcon: /media/season-4.png
siteYear: 2024
siteFooterlink: /about
showinSearchEngines: false
googleAnalyticsID: G-FMCYFTFPEL


# Set basic server info
serverName: Triad SMP (Season 4)
serverDescription: A Minecraft server by Dreamy!
serverIP: play.triadsmp.xyz
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/96J8mH6Mr7
discordServerID: 729569954537668698
discordChannelID: 1189263004794105918


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/